kind = "web"
previewPath = "/"
title = "Anovia"
version = "1.0.0"
id = "artifacts/anovia"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24755

[services.development]
run = "pnpm --filter @workspace/anovia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/anovia", "run", "build" ]
serve = "static"
publicDir = "artifacts/anovia/dist"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24755"
BASE_PATH = "/"
